version: "3"
services:
  web:
    container_name: barya_dashboard_nginx
    build: ./docker/nginx/
    ports:
      - "80:80"
    links:
      - phpfpm
    volumes:
      - ./:/usr/share/nginx/html
  phpfpm:
    container_name: barya_dashboard_phpfpm
    build: ./docker/php/
    ports:
      - "9000:9000"
    links:
      - mysql
    volumes:
      - ./:/usr/share/nginx/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini"
  mysql:
    container_name: barya_dashboard_mysql
    build: ./docker/mysql/
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db/dump.sql:/docker-entrypoint-initdb.d/dump.sql